In [2]:
import numpy as np
# Numpy 라이브러리를 불러와서 np라는 이름으로 사용하겠다는 의미

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [11]:
np.array(my_list)
# np.array()는 numpy안에 있는 메소드인 array()를 호출해서 사용하는데, 
# numpy를 np라는 이름으로 사용할 수 있으니, np.array()라는 식으로 사용할 수 있다. 


array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10)
# 0부터 시작해서 10개의 정수를 뽑아, 순차적으로 배열로 나타내라

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,11,2)
# 0부터 시작해 11개의 정수를 뽑아, 2씩 증가하는 순차적인 배열로 나타내라

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.arange(0,13,2)

array([ 0,  2,  4,  6,  8, 10, 12])

Built-in methods 

np. -> numpy 를 np라는 이름으로 저장해서 불러올 수 있으므로 사용 가능 


In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((3))

array([1., 1., 1.])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])